-- ===================================================================
-- V1: esquema inicial de StreamBox.
--
-- Escrito en SQL estándar para que funcione igual en PostgreSQL
-- (desarrollo y producción) y en H2 (tests).
--
-- Todo es idempotente (IF NOT EXISTS): las bases de datos creadas antes de
-- introducir Flyway (cuando Hibernate generaba el esquema con ddl-auto=update)
-- se adoptan sin errores y solo reciben lo que les falta (índices, claves
-- foráneas...). Ver spring.flyway.baseline-on-migrate.
-- ===================================================================

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT ck_users_role     CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS genres (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uk_genres_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS movies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    duration     INTEGER       NOT NULL,
    release_year INTEGER       NOT NULL,
    image_url    VARCHAR(500)  NOT NULL,
    video_url    VARCHAR(500)  NOT NULL,
    created_at   TIMESTAMP     NOT NULL,
    CONSTRAINT ck_movies_duration     CHECK (duration > 0),
    CONSTRAINT ck_movies_release_year CHECK (release_year BETWEEN 1888 AND 2100)
);

-- Géneros de cada película. Al borrar una película se borran sus filas aquí;
-- un género en uso por alguna película no se puede borrar (RESTRICT).
CREATE TABLE IF NOT EXISTS movie_genres (
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (movie_id, genre_id),
    CONSTRAINT fk_movie_genres_movie FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE,
    CONSTRAINT fk_movie_genres_genre FOREIGN KEY (genre_id) REFERENCES genres (id)
);

-- "Mi lista". En una base de datos nueva, al borrar un usuario o una película
-- desaparecen sus filas aquí por el ON DELETE CASCADE. (Las bases creadas antes
-- de Flyway conservan sus claves foráneas originales sin cascada, por eso
-- MovieService.deleteMovie sigue limpiando los favoritos explícitamente.)
CREATE TABLE IF NOT EXISTS user_favorite_movies (
    user_id  BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_favorites_user  FOREIGN KEY (user_id)  REFERENCES users (id)  ON DELETE CASCADE,
    CONSTRAINT fk_favorites_movie FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE
);

-- ===================================================================
-- Índices.
-- Las claves primarias compuestas solo sirven para buscar por su PRIMERA
-- columna; estos índices cubren las búsquedas por la segunda.
-- ===================================================================

-- Filtro por género (GET /api/movies/search?genreId=...)
CREATE INDEX IF NOT EXISTS idx_movie_genres_genre_id ON movie_genres (genre_id);

-- Borrado de una película: localizar sus favoritos
CREATE INDEX IF NOT EXISTS idx_favorites_movie_id ON user_favorite_movies (movie_id);

-- Filtro por año de lanzamiento (GET /api/movies/search?releaseYear=...)
CREATE INDEX IF NOT EXISTS idx_movies_release_year ON movies (release_year);
