-- ===================================================================
-- V3: series, episodios, géneros de cada serie y "Mi lista" de series.
--
-- Las series van en tablas PROPIAS, separadas de las películas: no se toca
-- ninguna tabla existente (movies, movie_genres, user_favorite_movies, users
-- ni genres), solo se añaden referencias nuevas hacia users y genres.
--
-- Las temporadas no tienen tabla: son un número dentro de cada episodio
-- (season_number). Una serie sin episodios existe (el administrador la crea
-- antes de subirlos) pero la aplicación la oculta a los usuarios con un
-- EXISTS sobre episodes; el índice único de episodes empieza por series_id,
-- así que ese EXISTS se resuelve con una búsqueda en el índice.
--
-- IMPACTO EN BASES EXISTENTES (incluida la de desarrollo en Supabase): esta
-- migración SOLO CREA tablas, restricciones e índices nuevos. No modifica ni
-- borra ninguna fila ni columna existente, así que es segura sobre una base
-- con datos. Las únicas dependencias hacia tablas antiguas son las claves
-- foráneas a users(id) y genres(id), que no cambian esas tablas.
-- Ojo: en Supabase, las tablas nuevas nacen sin RLS; hay que volver a aplicar
-- las políticas de seguridad del proyecto sobre ellas.
--
-- A diferencia de V1, aquí NO se usa IF NOT EXISTS: ninguna base anterior a
-- Flyway tenía estas tablas, y si alguien hubiera creado a mano una tabla
-- "series" con otra estructura es mejor que la migración falle de forma
-- visible a que la adopte en silencio y Hibernate la rechace después. Por la
-- misma razón todas las claves foráneas nuevas llevan su ON DELETE CASCADE
-- también en las bases adoptadas (no hay esquema heredado que conservar).
--
-- SQL estándar: funciona igual en PostgreSQL y en H2 (modo PostgreSQL).
-- ===================================================================

-- end_year NULL significa "en emisión". Los límites de año son los mismos
-- que en movies (1888 = primera película conservada; 2100 = tope razonable).
CREATE TABLE series (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR(150)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    release_year INTEGER       NOT NULL,
    end_year     INTEGER,
    image_url    VARCHAR(500)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_series              PRIMARY KEY (id),
    CONSTRAINT ck_series_release_year CHECK (release_year BETWEEN 1888 AND 2100),
    CONSTRAINT ck_series_end_year     CHECK (end_year IS NULL OR (end_year >= release_year AND end_year <= 2100))
);

-- Géneros de cada serie (mismo catálogo de géneros que las películas). Al
-- borrar una serie se borran sus filas aquí; un género en uso por alguna serie
-- NO se puede borrar (sin cascada: el servicio lo traduce a un 409), igual que
-- ocurre con movie_genres.
CREATE TABLE series_genres (
    series_id BIGINT NOT NULL,
    genre_id  BIGINT NOT NULL,
    CONSTRAINT pk_series_genres        PRIMARY KEY (series_id, genre_id),
    CONSTRAINT fk_series_genres_series FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE CASCADE,
    CONSTRAINT fk_series_genres_genre  FOREIGN KEY (genre_id)  REFERENCES genres (id)
);

-- Episodios. La temporada es solo un número; no puede haber dos episodios con
-- la misma temporada y número dentro de una serie (uk_episodes_...). La
-- sinopsis es opcional. Por ahora el episodio no tiene imagen propia (se usa la
-- de la serie); cuando la tenga llegará en una migración nueva.
-- Al borrar una serie se borran sus episodios (ON DELETE CASCADE).
CREATE TABLE episodes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    series_id      BIGINT        NOT NULL,
    season_number  INTEGER       NOT NULL,
    episode_number INTEGER       NOT NULL,
    title          VARCHAR(150)  NOT NULL,
    description    VARCHAR(1000),
    duration       INTEGER       NOT NULL,
    video_url      VARCHAR(500)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_episodes                PRIMARY KEY (id),
    CONSTRAINT fk_episodes_series         FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE CASCADE,
    CONSTRAINT uk_episodes_series_season_episode UNIQUE (series_id, season_number, episode_number),
    CONSTRAINT ck_episodes_season_number  CHECK (season_number >= 1),
    CONSTRAINT ck_episodes_episode_number CHECK (episode_number >= 1),
    CONSTRAINT ck_episodes_duration       CHECK (duration > 0)
);

-- "Mi lista" de series. Al borrar un usuario o una serie desaparecen sus filas
-- aquí (ON DELETE CASCADE, también en bases adoptadas: la tabla es nueva).
CREATE TABLE user_favorite_series (
    user_id   BIGINT NOT NULL,
    series_id BIGINT NOT NULL,
    CONSTRAINT pk_user_favorite_series PRIMARY KEY (user_id, series_id),
    CONSTRAINT fk_favorite_series_user   FOREIGN KEY (user_id)   REFERENCES users (id)  ON DELETE CASCADE,
    CONSTRAINT fk_favorite_series_series FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE CASCADE
);

-- ===================================================================
-- Índices.
-- Como en V1, las claves primarias compuestas solo sirven para buscar por su
-- PRIMERA columna; estos índices cubren las búsquedas por la segunda.
--
-- episodes no necesita índice aparte: uk_episodes_series_season_episode crea
-- un índice (series_id, season_number, episode_number) que sirve para
--   * listar los episodios de una serie ya ordenados por temporada y número,
--   * el EXISTS que oculta las series sin episodios,
--   * el borrado en cascada al borrar una serie (PostgreSQL no indexa solas
--     las columnas de una clave foránea).
-- ===================================================================

-- Filtro por género y recuento de series que usan un género (antes de borrarlo)
CREATE INDEX idx_series_genres_genre_id ON series_genres (genre_id);

-- Borrado de una serie: localizar sus favoritos para la cascada
CREATE INDEX idx_favorite_series_series_id ON user_favorite_series (series_id);

-- Filtro por año de estreno
CREATE INDEX idx_series_release_year ON series (release_year);
