-- ===================================================================
-- V4: refresh tokens (tarea 29: token de acceso de vida corta + refresh).
--
-- POR QUÉ
--   El token de acceso (JWT en la cookie HttpOnly) pasará a durar minutos. Para
--   no pedir la contraseña cada pocos minutos, el navegador recibe además un
--   refresh token de vida larga con el que obtiene tokens de acceso nuevos. A
--   diferencia del JWT, el refresh token SÍ se guarda en la base de datos: es
--   lo que permite revocarlo (cerrar sesión de verdad, en un dispositivo o en
--   todos) y detectar que alguien reutiliza uno robado.
--
-- MODELO (rotación por familias)
--   Cada login abre una "familia" (family_id). Cada refresh revoca el token
--   usado (revoked_at) y emite uno nuevo de la misma familia, apuntando del
--   viejo al nuevo (replaced_by_id). Si llega un token ya rotado fuera de la
--   pequeña "gracia" entre pestañas, es la señal de un robo: se revoca toda la
--   familia. family_expires_at es el tope absoluto de la sesión: rotar no la
--   alarga más allá de ese instante.
--
-- DECISIONES
--   * token_hash: SHA-256 del token en hexadecimal en minúsculas (64
--     caracteres). NUNCA se guarda el token en claro: quien lea la tabla (una
--     copia de seguridad, un volcado) no puede usarlo. El CHECK de formato
--     rechaza cualquier cosa que no sean 64 caracteres hexadecimales, así que
--     guardar por error el token en claro falla en la base de datos y no pasa
--     desapercibido. Basta un hash rápido (no BCrypt): el token es aleatorio y
--     largo, no una contraseña que se pueda adivinar por diccionario.
--   * family_id: UUID nativo (16 bytes en PostgreSQL; H2 también tiene el tipo
--     UUID). Ocupa menos que un VARCHAR(36) y la base de datos rechaza un valor
--     mal formado.
--   * created_at lo asigna la aplicación con el mismo reloj que expires_at (no
--     con @CreationTimestamp): los CHECK comparan ambas columnas y deben salir
--     del mismo Clock, también en los tests que lo fijan.
--   * Borrar un usuario borra sus refresh tokens (ON DELETE CASCADE): sus
--     sesiones dejan de existir con él.
--   * replaced_by_id es ON DELETE SET NULL: la limpieza periódica puede borrar
--     el token sucesor antes que su predecesor sin romper nada; el predecesor
--     sigue revocado (revoked_at), que es lo que importa para detectar la
--     reutilización.
--
-- IMPACTO EN BASES EXISTENTES (incluida la de desarrollo en Supabase): esta
-- migración SOLO CREA una tabla nueva con sus restricciones e índices. No
-- modifica ni borra ninguna fila ni columna existente. La única dependencia es
-- la clave foránea hacia users(id), que no cambia esa tabla. En una base
-- adoptada (anterior a Flyway) la tabla se crea igual de completa, con su
-- cascada. Como en V3, sin IF NOT EXISTS: ninguna base anterior tenía esta
-- tabla, y si existiera una con otra estructura es mejor fallar de forma
-- visible. En Supabase no hay que hacer nada a mano: el callback
-- afterMigrate__close_public_api.sql activa RLS y retira los privilegios de
-- anon/authenticated en todas las tablas de public tras cada migrate,
-- incluida esta.
--
-- SQL estándar: funciona igual en PostgreSQL y en H2 (modo PostgreSQL).
-- ===================================================================

CREATE TABLE refresh_tokens (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT      NOT NULL,
    token_hash        VARCHAR(64) NOT NULL,
    family_id         UUID        NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    family_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at        TIMESTAMP WITH TIME ZONE,
    replaced_by_id    BIGINT,
    CONSTRAINT pk_refresh_tokens            PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user        FOREIGN KEY (user_id)        REFERENCES users (id)          ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_replaced_by FOREIGN KEY (replaced_by_id) REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    -- 64 caracteres y solo 0-9a-f: TRANSLATE cambia cada uno de esos caracteres
    -- por '0', así que solo un hash válido queda en 64 ceros. No se usa una
    -- expresión regular (~ en PostgreSQL, REGEXP_LIKE en H2: no son portables)
    -- ni TRANSLATE con reemplazo vacío (H2 no borra los caracteres como PostgreSQL).
    CONSTRAINT ck_refresh_tokens_token_hash_format CHECK (
        CHAR_LENGTH(token_hash) = 64
        AND TRANSLATE(token_hash, '0123456789abcdef', '0000000000000000') = REPEAT('0', 64)),
    CONSTRAINT ck_refresh_tokens_expires_at        CHECK (expires_at > created_at),
    -- Un token nunca vive más que su familia (rotar no alarga la sesión)
    CONSTRAINT ck_refresh_tokens_family_expires_at CHECK (family_expires_at >= expires_at),
    -- Rotar = revocar: un token con sucesor tiene que estar revocado
    CONSTRAINT ck_refresh_tokens_replaced_revoked  CHECK (replaced_by_id IS NULL OR revoked_at IS NOT NULL),
    CONSTRAINT ck_refresh_tokens_not_self_replaced CHECK (replaced_by_id IS NULL OR replaced_by_id <> id)
);

-- ===================================================================
-- Índices. PostgreSQL NO indexa solas las columnas de una clave foránea.
--
-- La búsqueda por token (la de cada refresh) ya la cubre el índice que crea
-- uk_refresh_tokens_token_hash.
--
-- No hay índice para la limpieza de caducados (expires_at/family_expires_at):
-- es una tarea periódica sobre una tabla pequeña (sesiones vivas × rotaciones
-- recientes) y un recorrido secuencial de vez en cuando cuesta menos que
-- mantener dos índices más en cada refresh (un INSERT y un UPDATE). Además el
-- DELETE filtra por dos columnas con OR, así que necesitaría los dos. Si la
-- tabla creciera a millones de filas, se añadiría en una migración nueva.
-- ===================================================================

-- "Cerrar sesión en todos los dispositivos" y la cascada al borrar un usuario
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- Revocar una familia (logout de una sesión o reutilización detectada)
CREATE INDEX idx_refresh_tokens_family_id ON refresh_tokens (family_id);

-- ON DELETE SET NULL: al borrar un token, la base de datos busca qué tokens lo
-- tenían como sucesor. Sin este índice, la limpieza haría un recorrido
-- completo de la tabla por CADA fila borrada.
CREATE INDEX idx_refresh_tokens_replaced_by_id ON refresh_tokens (replaced_by_id);
