package com.emilio.streambox.postgres;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TimeZone;
import java.util.UUID;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.core.io.support.PropertiesLoaderUtils;
import org.testcontainers.junit.jupiter.Testcontainers;

import com.emilio.streambox.StreamboxApplication;
import com.emilio.streambox.entity.Movie;
import com.emilio.streambox.entity.User;
import com.emilio.streambox.repository.MovieRepository;
import com.emilio.streambox.repository.SeriesRepository;
import com.emilio.streambox.repository.UserRepository;
import com.emilio.streambox.service.MovieService;

/**
 * Adopción de una base de datos creada <b>antes de Flyway</b> (cuando Hibernate
 * generaba el esquema con {@code ddl-auto=update}) sobre PostgreSQL real.
 *
 * <p>
 * Es el escenario más delicado de las migraciones: una base con datos, sin
 * tabla {@code flyway_schema_history}, a la que Flyway debe "adoptar" con la
 * configuración real del proyecto ({@code baseline-on-migrate=true},
 * {@code baseline-version=0}, leídas de {@code application.properties} para que
 * el test no pueda desincronizarse de ella). H2 no puede reproducirlo con
 * fidelidad: aquí se comprueba con el comportamiento real de PostgreSQL.
 * </p>
 *
 * <p>
 * Cada test crea su propia base de datos vacía ({@code CREATE DATABASE}) dentro
 * del contenedor compartido y no toca la base del contexto principal de
 * Spring. Solo el último test levanta la aplicación completa sobre la base
 * adoptada.
 * </p>
 */
@Testcontainers(disabledWithoutDocker = true)
class PostgresBaselineAdoptionIntegrationTest {

    /**
     * Esquema tal como lo dejaba Hibernate (7.x, dialecto PostgreSQL) con las
     * entidades anteriores a Flyway: fechas {@code timestamp(6)} sin zona,
     * claves foráneas con nombre autogenerado y SIN {@code ON DELETE CASCADE},
     * restricciones de unicidad con nombre {@code UK...}, solo el CHECK del
     * enum de rol, y sin índices secundarios ni CHECK de año/duración.
     */
    private static final String LEGACY_SCHEMA = """
            create table genres (id bigint generated by default as identity, name varchar(50) not null, primary key (id));
            create table movies (id bigint generated by default as identity, created_at timestamp(6) not null,
                description varchar(1000) not null, duration integer not null, image_url varchar(500) not null,
                release_year integer not null, title varchar(150) not null, video_url varchar(500) not null,
                primary key (id));
            create table users (id bigint generated by default as identity, created_at timestamp(6) not null,
                email varchar(100) not null, password varchar(255) not null,
                role varchar(20) not null check (role in ('USER','ADMIN')),
                username varchar(50) not null, primary key (id));
            create table movie_genres (movie_id bigint not null, genre_id bigint not null, primary key (movie_id, genre_id));
            create table user_favorite_movies (user_id bigint not null, movie_id bigint not null, primary key (user_id, movie_id));
            alter table genres add constraint UKlegacy_genres_name unique (name);
            alter table users add constraint UKlegacy_users_email unique (email);
            alter table users add constraint UKlegacy_users_username unique (username);
            alter table movie_genres add constraint FKlegacy_mg_genre foreign key (genre_id) references genres;
            alter table movie_genres add constraint FKlegacy_mg_movie foreign key (movie_id) references movies;
            alter table user_favorite_movies add constraint FKlegacy_fav_movie foreign key (movie_id) references movies;
            alter table user_favorite_movies add constraint FKlegacy_fav_user foreign key (user_id) references users;
            """;

    /** Filas de ejemplo: la fecha 22:00 de junio ilustra la conversión de zona de V2. */
    private static final String LEGACY_DATA = """
            insert into genres (name) values ('Acción'), ('Drama');
            insert into users (username, email, password, role, created_at)
                values ('alice', 'alice@test.com', 'hash-a', 'USER', '2020-06-15 22:00:00'),
                       ('root',  'root@test.com',  'hash-r', 'ADMIN', '2021-01-10 08:30:00');
            insert into movies (title, description, duration, release_year, image_url, video_url, created_at)
                values ('Mañana', 'd1', 100, 1999, 'i1', 'v1', '2020-06-15 22:00:00'),
                       ('Alien',  'd2', 117, 1979, 'i2', 'v2', '2020-06-16 09:15:30');
            insert into movie_genres (movie_id, genre_id)
                select m.id, g.id from movies m, genres g where m.title = 'Alien' and g.name = 'Acción';
            insert into user_favorite_movies (user_id, movie_id)
                select u.id, m.id from users u, movies m where u.username = 'alice';
            """;

    // ------------------------------------------------------------------
    // Flyway sobre la base heredada
    // ------------------------------------------------------------------

    /**
     * La historia queda registrada: baseline en la versión 0 (por eso V1 SÍ se
     * ejecuta), luego V1, V2, V3 y V4, todas correctas. Una segunda ejecución no
     * hace nada y {@code validate} pasa (los checksums coinciden).
     */
    @Test
    void laAdopcionRegistraBaselineYTodasLasMigracionesYEsRepetible() throws Exception {
        String db = createDatabase(true);

        MigrateResult first = flyway(db).migrate();

        assertEquals(4, first.migrationsExecuted, "deben ejecutarse V1, V2, V3 y V4");
        List<Map<String, Object>> history = jdbc(db).queryForList(
                "SELECT version, description, type, success FROM flyway_schema_history ORDER BY installed_rank");
        assertEquals(List.of("0", "1", "2", "3", "4"), history.stream().map(r -> (String) r.get("version")).toList(), "" + history);
        assertEquals("BASELINE", history.get(0).get("type"));
        assertTrue(history.stream().allMatch(r -> Boolean.TRUE.equals(r.get("success"))));

        assertEquals(0, flyway(db).migrate().migrationsExecuted, "la segunda ejecución no debe hacer nada");
        flyway(db).validate();
    }

    /**
     * V1 es idempotente ({@code IF NOT EXISTS}) y no destruye datos: tras
     * adoptar, todas las filas y relaciones siguen ahí con los mismos valores
     * (incluido el texto con {@code ñ}).
     */
    @Test
    void laAdopcionConservaTodosLosDatos() throws Exception {
        String db = createDatabase(true);

        flyway(db).migrate();

        JdbcTemplate jdbc = jdbc(db);
        assertEquals(2, count(jdbc, "users"));
        assertEquals(2, count(jdbc, "movies"));
        assertEquals(2, count(jdbc, "genres"));
        assertEquals(1, count(jdbc, "movie_genres"));
        assertEquals(2, count(jdbc, "user_favorite_movies"), "alice tiene las dos películas");
        assertEquals(List.of("Alien", "Mañana"),
                jdbc.queryForList("SELECT title FROM movies ORDER BY title", String.class));
        assertEquals("hash-a", jdbc.queryForObject("SELECT password FROM users WHERE username = 'alice'", String.class));
        assertEquals(List.of("Acción", "Drama"),
                jdbc.queryForList("SELECT name FROM genres ORDER BY name", String.class));
    }

    /**
     * V1 completa lo que falta en la base heredada: los tres índices del
     * catálogo de películas (ver {@code idx_*}); {@code CREATE INDEX IF NOT
     * EXISTS} es lo único que V1 llega a añadir sobre tablas que ya existían.
     * Los otros son los de las tablas de series que crea V3 y los de
     * {@code refresh_tokens} que crea V4.
     */
    @Test
    void laAdopcionAnadeLosIndicesQueFaltaban() throws Exception {
        String db = createDatabase(true);
        JdbcTemplate jdbc = jdbc(db);
        assertEquals(List.of(), jdbc.queryForList(
                "SELECT indexname FROM pg_indexes WHERE schemaname = 'public' AND indexname LIKE 'idx\\_%'", String.class));

        flyway(db).migrate();

        // Se compara como conjunto: el orden de ORDER BY depende de la collation del servidor
        assertEquals(Set.of("idx_favorites_movie_id", "idx_movie_genres_genre_id", "idx_movies_release_year",
                        "idx_series_genres_genre_id", "idx_favorite_series_series_id", "idx_series_release_year",
                        "idx_refresh_tokens_user_id", "idx_refresh_tokens_family_id", "idx_refresh_tokens_replaced_by_id"),
                Set.copyOf(jdbc.queryForList("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'"
                        + " AND indexname LIKE 'idx\\_%'", String.class)));
    }

    /**
     * V2 convierte {@code created_at} a {@code timestamptz} conservando los
     * datos, pero PostgreSQL interpreta el valor antiguo (sin zona) <b>en la zona
     * horaria de la sesión que ejecuta la migración</b>. El driver JDBC envía la
     * zona de la JVM, así que el instante resultante depende de la máquina que
     * ejecute Flyway. Este test lo fuerza explícitamente con tres zonas y
     * documenta el resultado observado: {@code 22:00} de junio queda como
     * {@code 20:00Z} en Madrid (UTC+2), {@code 22:00Z} en UTC y {@code 02:00Z} del
     * día siguiente en Nueva York (UTC-4). Es el aviso que figura en la cabecera
     * de V2: si la base heredada se escribió con otra zona que la del servidor que
     * migra, las fechas quedan desplazadas (solo afecta a {@code created_at}).
     */
    @ParameterizedTest(name = "zona de la sesión {0}")
    @CsvSource({
            "Europe/Madrid,    2020-06-15T20:00:00Z",
            "UTC,              2020-06-15T22:00:00Z",
            "America/New_York, 2020-06-16T02:00:00Z" })
    void v2InterpretaLasFechasAntiguasEnLaZonaHorariaDeLaSesion(String zone, String expectedInstant) throws Exception {
        String db = createDatabase(true);

        TimeZone previous = TimeZone.getDefault();
        try {
            TimeZone.setDefault(TimeZone.getTimeZone(zone));
            flyway(db).migrate(); // la conexión nueva de Flyway hereda la zona de la JVM
        } finally {
            TimeZone.setDefault(previous);
        }

        JdbcTemplate jdbc = jdbc(db);
        assertEquals("timestamp with time zone", jdbc.queryForObject(
                "SELECT data_type FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'created_at'",
                String.class));
        Instant migrated = epoch(jdbc, "SELECT EXTRACT(EPOCH FROM created_at) FROM users WHERE username = 'alice'");
        assertEquals(Instant.parse(expectedInstant), migrated);
        // Y es exactamente "la hora antigua leída en esa zona": la regla se cumple para todas las filas
        Instant movieMigrated = epoch(jdbc, "SELECT EXTRACT(EPOCH FROM created_at) FROM movies WHERE title = 'Alien'");
        assertEquals(LocalDateTime.parse("2020-06-16T09:15:30").atZone(ZoneId.of(zone)).toInstant(), movieMigrated);
    }

    /**
     * Límite conocido de la adopción (se documenta, no se defiende): como V1 usa
     * {@code CREATE TABLE IF NOT EXISTS}, una base heredada conserva su esquema
     * original. Por tanto NO recibe (a) el {@code ON DELETE CASCADE} de las
     * tablas de unión ni (b) los CHECK de año y duración. Es exactamente lo que
     * dice la documentación de {@code MovieRepository.deleteFromAllFavorites}:
     * sin esa limpieza explícita, borrar una película con favoritos fallaría con
     * una violación de clave foránea. Si algún día se añade una migración que
     * unifique ambos esquemas, este test debe actualizarse.
     */
    @Test
    void laBaseAdoptadaNoRecibeLasCascadasNiLosCheckDeUnaBaseNueva() throws Exception {
        String db = createDatabase(true);
        flyway(db).migrate();
        JdbcTemplate jdbc = jdbc(db);

        // Solo las cuatro claves foráneas heredadas (las de V3 son nuevas y sí cascadan)
        assertEquals(List.of("NO ACTION", "NO ACTION", "NO ACTION", "NO ACTION"), jdbc.queryForList(
                "SELECT delete_rule FROM information_schema.referential_constraints"
                        + " WHERE constraint_schema = 'public' AND constraint_name LIKE 'fklegacy%'"
                        + " ORDER BY constraint_name", String.class));

        // Borrar una película con favoritos falla en la base heredada (en una nueva se encadena)
        DataIntegrityViolationException error = assertThrows(DataIntegrityViolationException.class,
                () -> jdbc.update("DELETE FROM movies WHERE title = 'Mañana'"));
        assertEquals("23503", PostgresIntegrationTestSupport.sqlState(error));

        // Y acepta un año imposible porque no tiene el CHECK de V1
        jdbc.update("INSERT INTO movies (title, description, duration, release_year, image_url, video_url, created_at)"
                + " VALUES ('Antigua', 'd', 100, 1700, 'u', 'v', now())");
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM movies WHERE release_year = 1700", Integer.class));
    }

    /**
     * A diferencia de las tablas de películas, las de series (V3) son nuevas
     * también en una base adoptada: se crean completas, con sus cascadas y sus
     * CHECK. Por eso, para series, no hace falta el equivalente de
     * {@code MovieRepository.deleteFromAllFavorites}: borrar una serie arrastra
     * episodios, géneros de la serie y favoritos aunque la base sea heredada, y
     * un género que use una serie sigue sin poder borrarse.
     */
    @Test
    void laBaseAdoptadaRecibeLasTablasDeSeriesCompletasConSusCascadas() throws Exception {
        String db = createDatabase(true);
        flyway(db).migrate();
        JdbcTemplate jdbc = jdbc(db);

        Map<String, String> rules = new java.util.HashMap<>();
        jdbc.queryForList("SELECT constraint_name, delete_rule FROM information_schema.referential_constraints"
                        + " WHERE constraint_schema = 'public'")
                .forEach(r -> rules.put((String) r.get("constraint_name"), (String) r.get("delete_rule")));
        assertEquals("CASCADE", rules.get("fk_series_genres_series"));
        assertEquals("NO ACTION", rules.get("fk_series_genres_genre"));
        assertEquals("CASCADE", rules.get("fk_episodes_series"));
        assertEquals("CASCADE", rules.get("fk_favorite_series_user"));
        assertEquals("CASCADE", rules.get("fk_favorite_series_series"));

        long seriesId = jdbc.queryForObject("INSERT INTO series (title, description, release_year, image_url, created_at)"
                + " VALUES ('Heredada', 'd', 2010, 'u', now()) RETURNING id", Long.class);
        jdbc.update("INSERT INTO episodes (series_id, season_number, episode_number, title, duration, video_url, created_at)"
                + " VALUES (?, 1, 1, 't', 40, 'v', now())", seriesId);
        jdbc.update("INSERT INTO series_genres (series_id, genre_id) SELECT ?, id FROM genres WHERE name = 'Drama'", seriesId);
        jdbc.update("INSERT INTO user_favorite_series (user_id, series_id) SELECT id, ? FROM users WHERE username = 'alice'",
                seriesId);

        // El género Drama (de la base heredada) ya no se puede borrar: lo usa la serie
        DataIntegrityViolationException error = assertThrows(DataIntegrityViolationException.class,
                () -> jdbc.update("DELETE FROM genres WHERE name = 'Drama'"));
        assertEquals("23503", PostgresIntegrationTestSupport.sqlState(error));

        // Borrar la serie arrastra todo lo suyo, sin tocar a alice ni el género
        jdbc.update("DELETE FROM series WHERE id = ?", seriesId);
        assertEquals(0, count(jdbc, "episodes"));
        assertEquals(0, count(jdbc, "series_genres"));
        assertEquals(0, count(jdbc, "user_favorite_series"));
        assertEquals(2, count(jdbc, "users"));
        assertEquals(2, count(jdbc, "genres"));
        // Y el CHECK de año de V3 también existe en la base adoptada
        assertEquals("23514", PostgresIntegrationTestSupport.sqlState(assertThrows(DataIntegrityViolationException.class,
                () -> jdbc.update("INSERT INTO series (title, description, release_year, image_url, created_at)"
                        + " VALUES ('Antigua', 'd', 1700, 'u', now())"))));
    }

    /**
     * {@code refresh_tokens} (V4) también es nueva en una base adoptada: se crea
     * completa y su clave foránea hacia el {@code users} HEREDADO sí cascada.
     * Borrar un usuario antiguo borra sus sesiones aunque sus favoritos de
     * películas (FK heredada sin cascada) impidieran borrarlo; aquí se usa
     * {@code root}, que no tiene favoritos.
     */
    @Test
    void laBaseAdoptadaRecibeRefreshTokensConSuCascadaHaciaElUsuarioHeredado() throws Exception {
        String db = createDatabase(true);
        flyway(db).migrate();
        JdbcTemplate jdbc = jdbc(db);

        Map<String, String> rules = new java.util.HashMap<>();
        jdbc.queryForList("SELECT constraint_name, delete_rule FROM information_schema.referential_constraints"
                        + " WHERE constraint_schema = 'public'")
                .forEach(r -> rules.put((String) r.get("constraint_name"), (String) r.get("delete_rule")));
        assertEquals("CASCADE", rules.get("fk_refresh_tokens_user"));
        assertEquals("SET NULL", rules.get("fk_refresh_tokens_replaced_by"));

        jdbc.update("INSERT INTO refresh_tokens (user_id, token_hash, family_id, created_at, expires_at, family_expires_at)"
                + " SELECT id, ?, gen_random_uuid(), now(), now() + interval '1 day', now() + interval '30 days'"
                + " FROM users WHERE username = 'root'", "a".repeat(64));
        assertEquals(1, count(jdbc, "refresh_tokens"));

        jdbc.update("DELETE FROM users WHERE username = 'root'");
        assertEquals(0, count(jdbc, "refresh_tokens"));
        assertEquals(1, count(jdbc, "users"));
    }

    /**
     * Contraste: una base vacía NO recibe fila de baseline (solo V1 a V4) y
     * sí tiene cascadas y CHECK. Garantiza que los dos caminos de arranque
     * producen lo que describe cada test.
     */
    @Test
    void unaBaseVaciaNoRegistraBaselineYRecibeCascadasYCheck() throws Exception {
        String db = createDatabase(false);

        flyway(db).migrate();

        JdbcTemplate jdbc = jdbc(db);
        assertEquals(List.of("1", "2", "3", "4"), jdbc.queryForList(
                "SELECT version FROM flyway_schema_history ORDER BY installed_rank", String.class));
        // Ocho claves foráneas en cascada. V1: géneros->película, favoritos->usuario y
        // favoritos->película. V3: géneros->serie, episodios->serie, favoritos de
        // series->usuario y favoritos de series->serie. V4: refresh tokens->usuario
        // (la del sucesor, fk_refresh_tokens_replaced_by, es SET NULL y no cuenta).
        assertEquals(8, jdbc.queryForObject(
                "SELECT COUNT(*) FROM information_schema.referential_constraints"
                        + " WHERE constraint_schema = 'public' AND delete_rule = 'CASCADE'", Integer.class));
        assertThrows(DataIntegrityViolationException.class, () -> jdbc.update(
                "INSERT INTO movies (title, description, duration, release_year, image_url, video_url, created_at)"
                        + " VALUES ('Antigua', 'd', 100, 1700, 'u', 'v', now())"));
    }

    // ------------------------------------------------------------------
    // Aplicación completa sobre la base adoptada
    // ------------------------------------------------------------------

    /**
     * Arranca la aplicación real (Flyway de Spring Boot + Hibernate con
     * {@code ddl-auto=validate}) contra la base heredada y comprueba que:
     * arranca, lee los datos antiguos (con la fecha ya como {@link Instant}) y
     * que borrar una película con favoritos funciona gracias a
     * {@code deleteFromAllFavorites} aunque las claves foráneas heredadas no
     * tengan cascada.
     */
    @Test
    void laAplicacionArrancaSobreUnaBaseAdoptadaYSigueBorrandoPeliculasConFavoritos() throws Exception {
        String db = createDatabase(true);
        PostgresIntegrationTestSupport.postgres(); // asegura el contenedor en marcha

        try (ConfigurableApplicationContext context = new SpringApplication(StreamboxApplication.class).run(
                "--spring.profiles.active=test",
                "--spring.datasource.url=" + url(db),
                "--spring.datasource.username=" + PostgresIntegrationTestSupport.postgres().getUsername(),
                "--spring.datasource.password=" + PostgresIntegrationTestSupport.postgres().getPassword(),
                "--spring.datasource.driver-class-name=org.postgresql.Driver",
                "--server.port=0")) {

            // Si Hibernate no hubiera validado el esquema adoptado, no habría llegado hasta aquí
            MovieRepository movies = context.getBean(MovieRepository.class);
            UserRepository users = context.getBean(UserRepository.class);
            MovieService movieService = context.getBean(MovieService.class);

            User alice = users.findByEmail("alice@test.com").orElseThrow();
            assertNotNull(alice.getCreatedAt());
            assertEquals(2, users.findFavoriteMovies(alice.getId()).size());
            // Las entidades de V3 (Series, Episode) también validan contra la base adoptada
            SeriesRepository series = context.getBean(SeriesRepository.class);
            assertEquals(0, series.count());
            assertEquals(List.of(), series.findFavoritesByUserId(alice.getId()));
            Movie manana = movies.findAllByTitleIgnoreCase("MAÑANA").get(0);
            assertEquals(1999, manana.getReleaseYear());

            movieService.deleteMovie(manana.getId());

            assertEquals(1, users.findFavoriteMovies(alice.getId()).size());
            assertEquals(1, movies.count());
        }
    }

    // ------------------------------------------------------------------
    // Utilidades: bases de datos temporales dentro del contenedor
    // ------------------------------------------------------------------

    /**
     * Crea una base de datos nueva y, si se pide, le aplica el esquema heredado
     * con datos. Todas se eliminan con el contenedor.
     */
    private static String createDatabase(boolean legacy) throws SQLException {
        String name = "adopt_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection admin = DriverManager.getConnection(
                PostgresIntegrationTestSupport.postgres().getJdbcUrl(),
                PostgresIntegrationTestSupport.postgres().getUsername(),
                PostgresIntegrationTestSupport.postgres().getPassword());
                Statement statement = admin.createStatement()) {
            statement.execute("CREATE DATABASE " + name);
        }
        if (legacy) {
            try (Connection connection = DriverManager.getConnection(url(name),
                    PostgresIntegrationTestSupport.postgres().getUsername(),
                    PostgresIntegrationTestSupport.postgres().getPassword());
                    Statement statement = connection.createStatement()) {
                // Se ejecutan sentencia a sentencia (el driver admite varias separadas por ';')
                statement.execute(LEGACY_SCHEMA);
                statement.execute(LEGACY_DATA);
            }
        }
        return name;
    }

    private static String url(String database) {
        var postgres = PostgresIntegrationTestSupport.postgres();
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + database
                + "?loggerLevel=OFF";
    }

    private static JdbcTemplate jdbc(String database) {
        var postgres = PostgresIntegrationTestSupport.postgres();
        return new JdbcTemplate(new DriverManagerDataSource(url(database), postgres.getUsername(), postgres.getPassword()));
    }

    /**
     * Flyway configurado como la aplicación: mismas migraciones y los valores
     * {@code spring.flyway.baseline-*} leídos de {@code application.properties}.
     */
    private static Flyway flyway(String database) throws IOException {
        Properties properties = PropertiesLoaderUtils.loadProperties(new ClassPathResource("application.properties"));
        assertEquals("true", properties.getProperty("spring.flyway.baseline-on-migrate"));
        var postgres = PostgresIntegrationTestSupport.postgres();
        return Flyway.configure()
                .dataSource(url(database), postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(Boolean.parseBoolean(properties.getProperty("spring.flyway.baseline-on-migrate")))
                .baselineVersion(properties.getProperty("spring.flyway.baseline-version"))
                .load();
    }

    private static int count(JdbcTemplate jdbc, String table) {
        return jdbc.queryForObject("SELECT COUNT(*) FROM " + table, Integer.class);
    }

    private static Instant epoch(JdbcTemplate jdbc, String sql) {
        return Instant.ofEpochMilli(Math.round(jdbc.queryForObject(sql, Double.class) * 1000));
    }
}
